### ISSUE TITLE
Selenium driver names

### ISSUE THREAD

**Issue by chrwen-omicron** [agabrys/chocolatey-packages#1]
Hi,
Why would you change the names of the drivers? Selenium is using them as default value ...

**Comment by agabrys** [comment]
Hi,
Honestly I didn't know that Selenium looks for them under these names. I will try to restore default names in this week. Of course all drivers still will be extracted to one directory.

Regards

**Comment by chrwen-omicron** [comment]
Well it's not a big deal, I was just curious.

Check the `__init__` method of the `WebDriver`class in https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/chrome/webdriver.py and https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/ie/webdriver.py.
The default values are chromedriver and IEDriverServer.exe.

Thanks for those packages, keep it up!

**Comment by agabrys** [comment]
Done.

Status:
- `ie`, `chrome` and `opera`: waiting for moderation
- `all`: I will push it, when `ie`, `chrome` and `opera` will be approved

**Comment by chrwen-omicron** [comment]
Nice, thanks!
