### ISSUE TITLE
selenium drivers - add geckodriver

### ISSUE THREAD

**Issue by davehunt** [agabrys/chocolatey-packages#14]
I just came across your chocolatey packages, and thought it might be useful to have one for Mozilla's geckodriver: https://github.com/mozilla/geckodriver/releases

**Comment by agabrys** [comment]
Done.
- [selenium-gecko-driver](https://chocolatey.org/packages/selenium-gecko-driver) waiting for moderation
- [selenium-all-drivers](https://chocolatey.org/packages/selenium-all-drivers) I will push it after approval of the `selenium-gecko-driver` package
