### ISSUE TITLE
Selenium Grid Package

### ISSUE THREAD

**Issue by dhoer** [agabrys/chocolatey-packages#15]
Thanks for creating the selenium driver packages.  I was wondering if you plan to create a selenium cookbook that will install the selenium jar?  I also would like get your thoughts on how to implement it.

I'm the author of https://github.com/dhoer/chef-selenium and would like to migrate off of configuration management tools and use docker for linux and choco for windows (since we need access to a gui).   

I would like to have something similar to what chef-selenium does where a hub service and node gui service can be installed on windows.  Based on what I understand about chocolatey it could have the following basic behavior:

Install standalone service: `choco install seleniumgrid`
Install selenium hub service: `choco install seleniumgrid --params "'/Hub'"`
Install selenium grid gui service: `choco install seleniumgrid --params "'/Node'"`

Package params could also be used to configure both the hub and node [json](https://github.com/SeleniumHQ/selenium/issues/3794#issuecomment-293673986)  via [templates](https://stackoverflow.com/a/1667944/4548096).

For example:
- `/URL` - the url that will be used to post the registration request.This option takes precedence over /HubHost and /HubPort options. Default: http://localhost:4444
- `/ChromeMaxInstances` - number of Chrome instances - defaults to `0`
- `/ChromeAutoVersion` - determine firefox browser version - defaults to `ChromeVersion` param if unable to determine version automatically
- `/ChomeVersion` - version of chrome browser - defaults to `''`

Note the ChromeAutoVersion extra functionality can be pulled from https://chocolatey.org/packages/GoogleChrome Get-ChromeVersion() function in helpers.ps1

So a call could possibly look like this:
```
choco install seleniumgrid --params "'/Node /Url:http://selenium.example.com:4444 /Log:C:/selenium/log/node.log /MaxSession:5 /ChromeMaxInstances:5 /ChromeAutoVersion'"
```
And it looks like 0.10.8 will allow you to disable auto-uninstall, which will be nice when working with jar files https://stackoverflow.com/a/45871423/4548096

I prefer tha java not be a dependency to allow for users flexibility to install jre or jdk as 32 or 64 bit.  The install should fail if java is not available.

What are your thoughts about this and are you interested and collaborating on creating this?
Thanks,
Dennis

**Comment by agabrys** [comment]
Hi Dennis,
Thank you for your detailed message. Now I'm working on 4 other projects and unfortunately I will not find more time for next one.

There is an official chocolatey project where people can make requests for new packages: https://github.com/chocolatey/chocolatey-package-requests. I think it is a good place for your proposal. I hope that you find someone there very soon.

Regards
Adam Gabryś

**Comment by dhoer** [comment]
FYI, this is in moderation on chocolatey.org https://github.com/dhoer/choco-selenium.  It should be available sometime soon.

**Comment by dhoer** [comment]
If you have any feedback on this package, please feel free to open up an issue on it.

**Comment by dhoer** [comment]
@agabrys Are you interested in being a collaborator on Selenium.  It seems you are on top of getting releases out as soon as they are published. I probably won't be.

**Comment by agabrys** [comment]
@dhoer I see that you did a lot of work 👍

Thank you for the offer, but I don't use Selenium, so I don't want to be a collaborator. I maintain most of my packages (e.g. Freemake Video Converter is not maintained) which I created some time ago, but I don't want to invest more time.

Cheers

**Comment by dhoer** [comment]
I totally understand ;-) Thanks anyway
