### ISSUE TITLE
On windows 2012r2 vagrant box, none of the selenium-*-drivers seem to work

### ISSUE THREAD

**Issue by dhoer** [agabrys/chocolatey-packages#17]
On windows 2012r2 vagrant box, none of the selenium-*-drivers seem to work.  When I swap out chromedriver for selenium-chrome-driver, chrome tests then pass: https://github.com/dhoer/choco-selenium/blob/vagrant/vagrant-provision-grid.ps1#L8.  

All fail with similar message: 
```
Unable to create new service: ChromeDriverService
Unable to create new service: InternetExplorerDriverService
Unable to create new service: GeckoDriverService
```

**Comment by agabrys** [comment]
It looks like a problem with privileges or Selenium version. Check this:
* https://github.com/SeleniumHQ/selenium/issues/4498
* https://github.com/facebook/php-webdriver/issues/464

**Comment by dhoer** [comment]
I'm using selenium 3.6.0 and chrome will work with chromedriver, but not selenium-chrome-driver. The selenium-chrome-driver throws the same error as the other selenium-*-driver packages.  So I think it is how these are implemented.  Chromedriver must do something extra the selenium-*-drivers don't.  I can run test cases on vagrant an get consistent results https://github.com/dhoer/choco-selenium/blob/vagrant/TESTING.md.

Comparing chromedriver https://chocolatey.org/packages/chromedriver to selenium-chrome-driver, it looks similar and it looks like chromedriver packageName is missing the $ prefix, but it works.

**Comment by dhoer** [comment]
It looks like it shims the chromedriver in somehow. I see this in the output:
ShimGen has successfully created a shim for chromedriver.exe

**Comment by agabrys** [comment]
chromedriver package is unziped to ‚toolsDir’. My packages are installed in ‚toolsDir/selenium’ directory. Maybe you need to grant your user additional permissions to ‚selenium’ subdirectory?

**Comment by agabrys** [comment]
Ok. This could be a reason. You can add ‚toolsDir/selenium’ to PATH environment and then they should work. I’ll try to add shim for my packages.

**Comment by dhoer** [comment]
I don't see that output for selenium-*-driver

**Comment by dhoer** [comment]
Thanks 👍

**Comment by agabrys** [comment]
I've added shim support and cleaned scripts of `selenium-chrome-driver` package.
I'll do this for all selenium packages today.

**Comment by dhoer** [comment]
Tested out the latest selenium chrome driver, it  works great! Thanks

I will test the others and close this issue once they are published.

**Comment by agabrys** [comment]
I've updated all `selenium-*-driver` packages:

* [Selenium Chrome Driver 2.33.20171103](https://chocolatey.org/packages/selenium-chrome-driver/2.33.20171103)
* [Selenium Edge Driver 5.16299.20171103 ](https://chocolatey.org/packages/selenium-edge-driver/5.16299.20171103)
* [Selenium Gecko Driver 0.19.1.20171103 ](https://chocolatey.org/packages/selenium-gecko-driver/0.19.1.20171103)
* [Selenium Internet Explorer Driver 3.6.0.20171103](https://chocolatey.org/packages/selenium-ie-driver/3.6.0.20171103)
* [Selenium Opera Driver 2.30.20171103](https://chocolatey.org/packages/selenium-opera-driver/2.30.20171103)

**Comment by dhoer** [comment]
All but edge and opera has been verified!  Thanks again
