### ISSUE TITLE
Burp Suite Pro Edition

### ISSUE THREAD

**Issue by Jnchi** [agabrys/chocolatey-packages#22]
How can I install Burp Pro via chocolatey?

See: https://support.portswigger.net/customer/portal/questions/17574918-burp-suite-pro-edition-on-chocolatey

**Comment by agabrys** [comment]
I don't see any package which allows installing Pro Edition, so the answer is you cannot. I don't plan to add such package (at this moment I even don't use the Free Edition). You can write to PortSwigger and ask them for a such option. You should probably use this form to contact them: https://support.portswigger.net/customer/portal/questions/new?qna[kb_topic_id]=719256

All available Burp packages: https://chocolatey.org/packages?q=burp
