### ISSUE TITLE
Upgrade IEDriver to 3.141.59

### ISSUE THREAD

**Issue by conradolega** [agabrys/chocolatey-packages#23]
It's not advertised on the Selenium site for some reason, but you can find it on the [releases page](https://selenium-release.storage.googleapis.com/index.html?path=3.141/).

**Comment by agabrys** [comment]
Hello. I didn't have time to reply because I moved to a new flat. I hope I'll be able to update the package this week 👍

**Comment by agabrys** [comment]
Hi, the version has been pushed: https://chocolatey.org/packages/selenium-ie-driver/3.141.59
