### ISSUE TITLE
Freemake installers are not silent (requires click on Finish button and open website in browser)

### ISSUE THREAD

**Issue by agabrys** [agabrys/chocolatey-packages#3]
Flatlinebb:

> I would like to suggest that the target download be the full version of the installer:
> http://download.freemake.net/FreemakeOriginals2/FreemakeVideoConverterFull.exe
> 
> Instead of the downloader installer:
> http://download.freemake.net/FreemakeOriginals2/FreemakeVideoConverterSetup.exe
> 
> EDIT: Also, the /VERYSILENT switch doesn't seem to be working correctly as the installer GUI popped up on my screen and sat there after downloading and running the install file until I clicked Finish. I know getting this information out of Freemake can be difficult, as I have tried once to talk to them directly about their installer and the idea of a fully silent installer, that does not launch a web browser afterwards, was totally alien to them. They literally responded, asking me what nefarious purposes required a silent installer - was I trying to steal their software and sell as my own? I guess the idea of a repository like chocolatey just wasn't as popular back then. They might be more cooperative today.

Link to [disqus](https://disqus.com/) discussion: http://disq.us/p/1aefzht

Requires changes in:
- freemake-audio-converter
- freemake-video-converter

**Comment by agabrys** [comment]
I wrote an e-mail to Freemake:

> Hello,
> I'm a maintainer of the Freemake Audio Converter and Freemake Viedo Converter packages for chocolatey (chocolatey.org) - package manager for Windows. Now packages enable installation of the applications, but do not perform it in a manner consistent with packages managers:
> - installation should not require user interaction (now user must click finish button and close browser window)
> - package should allow to install concrete version (now always install the latest version)
> 
> Is there any chance that Freemake will:
> - handles installers /VERYSILENT parameter in proper way
> - publish downloadable installers for concrete version (e.g. freemake-audio-converter-1.1.8.3.exe)
> 
> Links:
> https://chocolatey.org/packages/freemake-audio-converter
> https://chocolatey.org/packages/freemake-video-converter
> 
> Regards,
> Adam Gabryś

**Comment by agabrys** [comment]
Freemake responded:

> Hello,
> 
> thanks for supporting Freemake.
> sorry, but these options are currently not planned.

**Comment by flatlinebb** [comment]
Thanks for trying. Told you Freemake folks were behind the times :(
